# Generated by Django 4.0.1 on 2022-01-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_id',
            field=models.IntegerField(default=1),
        ),
    ]
