# Generated by Django 4.0.1 on 2022-01-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='books.Authors'),
        ),
    ]
